### ISSUE TITLE
Run Croawl

### ISSUE THREAD

**Issue by fratak** [dissemin/croawl#2]
How do I build and run Croawl?

**Comment by wetneb** [comment]
Hi @fratak, this software is still a work in progress that is not packaged properly, and poorly documented.

If you are interested in the learning algorithm, it is all contained in the `urltheory` module. Many unit tests are provided in https://github.com/dissemin/croawl/blob/master/urltheory/tests.py to get an idea of how it works.

**Comment by fratak** [comment]
Excellent stuff! Thanks
